
development:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: fispo
  pool: 5
  username: suser
  password: s
  host: localhost

test:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: fispo
  pool: 5
  username: root
  password: s
  host: localhost

production:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: fispo
  pool: 5
  username: root
  password: s
  host: localhost

  timeout: 5000
